version: "3.18"

services:
  postgres:
    image: postgres:17.6
    container_name: keycloak-postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.5
    container_name: keycloaklocal
    command: ["start-dev"]
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # sql2:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: sql2
  #   hostname: sql2
  #   environment:
  #       - ACCEPT_EULA=Y
  #       - SA_PASSWORD=@Bcd.1234
  #   ports:
  #       - "1433:1433"
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: reactivities_api
  #   ports:
  #     - "5071:8080"
  #   depends_on:
  #     - keycloak
  #     - sql2
  #     - postgres
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:8080
  #     - ConnectionStrings__default=Server=sql2,1433;Database=reactivities4;User Id=sa;Password=@Bcd.1234;TrustServerCertificate=True
  #     - Issuer=http://keycloak:8080/realms/reactivities_realm

volumes:
  postgres_data:
  keycloak-data:
  sqlserver_data:
